server:
  port: 8090

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      routes:
        - id: ms-users
          uri: lb://ms-users
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=2
      default-filters:
        - TokenRelay
  security:
    oauth2:
      client:
        provider:
          keycloak-gateway:
            issuer-uri: http://localhost:8080/realms/ticketrek
        registration:
          keycloak-gateway:
            client-id: api-gateway-client
            client-secret: mbUrQfgEcBT6ALFMMg3sHqFSm3yezdMc
            scope:
              - openid
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8090/login/oauth2/code/keycloak